### ISSUE TITLE
--max-cpu-usage=100

### ISSUE THREAD

**Issue by h1rule** [holzmaster/pr0gramm-miner-native#4]
Hey,

wollte das auf 10 stellen, aber er benutzt immer =100

:(

**Comment by h1rule** [comment]
jo?

**Comment by fwaechter** [comment]
In der Datei run.sh die unterste Zeile anpassen: `--max-cpu-usage=10` oder halt eine Variable dafür erstellen und diese einfügen.

**Comment by holzmaster** [comment]
Was @fwaechter sagt.
