### ISSUE TITLE
Bekomme es nicht zum laufen

### ISSUE THREAD

**Issue by CrushTub3** [holzmaster/pr0gramm-miner-native#8]
Tachchen,

also entweder bin ich zu blöd oder es funktioniert tatsächlich nicht.

Ich bin absoluter Anfänger mit Docker und habe es eben mal auf meinem VPS installiert.
Die paar Schitte aus der Readme.md habe ich ausgeführt.

Wenn ich `[sudo] docker run -e PR0GRAMM_USER=username <image>` ausführe bekomme ich als Meldung: -bash: syntax error near unexpected token `newline'

Ich als Laie habe dann einfach mal statt image alpine genommen. Da wird etwas ausgeführt, jedoch ohne Output. Nach 3 Sekunden bricht dies dann auch ohne Meldung ab.

Was mache ich falsch?

**Comment by holzmaster** [comment]
Du musst für `<image>` die Image-ID angeben, die ganz unten bei `docker build .` rausfällt.

Oder du taggst das Image nach dem Build:
```Shell
docker build -t miner .
docker run -e PR0GRAMM_USER=username miner
```
